FROM ubuntu:16.04.7
RUN apt-get install -y --no-install-recommends nginx=1.21.2 
# RUN ???start service
# ENV NAME=Aksholpan
# VOLUME /var/www/html
# WORKDIR /var/www/html
# # RUN rm index.html
# COPY index.html .
# COPY team1.png .
CMD ["nginx", "-g", "daemon off;"]
# SHELL ["/bin/bash", "-c"]

# USER aksholpan
# STOPSIGNAL SIGSTOP
