# Use an official PostgreSQL image as a parent image
FROM postgres:latest
VOLUME /postgres
# Set the environment variables for PostgreSQL
ENV POSTGRES_USER aksholpan
# ENV POSTGRES_PASSWORD password


# Expose the PostgreSQL port
EXPOSE 5432

